# Название приложения
spring.application.name=purchase-requests

# Подключение к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/purchase_requests_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Настройка Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Настройка Liquibase - главный чейнджлог
spring.liquibase.change-log=classpath:liquibase/db/changelog-cumulative.xml

# Настройка Vaadin - автоматическое открытие в браузере
vaadin.launch-browser=true

# Порт приложения
server.port=8080